name: Release

on:
  push:
    branches: ["main"]

jobs:
  test:
    uses: inngest/inngestgo/.github/workflows/go.yml@main

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: Create Git Tag
        run: |
          git config user.name "inngest-release-bot"
          git config user.email "126702797+inngest-release-bot@users.noreply.github.com"

          VERSION="$(go run scripts/get_version/main.go)"
          git tag "v${VERSION}"
          git push origin "v${VERSION}"
