name: Release

on:
  push:
    branches:
      - main
      - "v*.x"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          # Used to fetch all history so that changesets doesn't attempt to
          # publish duplicate tags.
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - run: npm ci
        working-directory: release

      # Replaces `concurrency` - never cancels any jobs
      - uses: softprops/turnstyle@v2
        with:
          poll-interval-seconds: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: changesets/action@v1
        with:
          version: npm run release:version
          publish: npm run release:publish
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_GITHUB_TOKEN }}
